apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB1YOnNg/8vx73bc4d4mE6sJZO4kwqFaGabAZtfBpK95tksAbhGn3Me0PYOXvPB9XWeyNahFvpFyCDYpzm2F9a27LgQN5ArwSm6Y7A6NfUC8ndMuHSswX5Nj7tHY/oLkCXQG9Knr16kfWUcxEH+Gqn+UsQwxZ0YWGT0xzmRO+o6yNOEZ7BuUD1fiXa3rzUiAveUiOuj94ILFk14V+n3JGuTgUbpRHek7W1aTGfjeg4eRih7zLfN1uZd8LreAJLgw23o/7eOy7i+HUEAMctT9XJRrMu+GmcoCdnrLP/a9DNub4SDIGR+/IqGGTPFlSzw/j0q0VCVuWyGchhfETNnGJrIBEam08BcfS/RXqpXwPB2ZRpaTfK4GZ01s2n3ImrBVur86DdYJmDaL6aRCKGPmCc13LhIhdp6CandASMp8x96oKYbj/STuTd15lfiA1K8QFJppQM/Et32rbOOL9ZbZRca0wLr7weurjO1EKDVDRajPmGrYcD2QZJJjc+B+95Sypn+yEmOx5AcQeBODRUVxo9RDaav+fdkB4aVkj6OgKz3P4Pv7h35tciJSFrjJNFsTHwuIBxPUD0FTrpK0v+UlgViNXZYzumoU/v/jRU3fN0EkWBdfkFMf/epB6fbsTVSpsVsmUOCKHVQ+W7BXVdoNWfC4ysAB5/0Rf49M0DW0MvAbR3fPc05BOp/desoaMPKRbMEggE24vqKO8Sn7gc2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque

